services:
  - type: web
    name: voting-backend
    runtime: docker
    build:
      dockerfile: Dockerfile
      build_pack_version: 2
    autoDeploy: true
    scaling:
      replicas: 1
      concurrency: 100