services:
  - type: web
    name: voting-backend
    runtime: docker
    build:
      dockerfile: Dockerfile
    envVars:
      - key: INFURA_PROJECT_ID
        value: your_infura_project_id
      - key: PRIVATE_KEY
        value: your_private_key
    scaling:
      replicas: 1
      concurrency: 100